name: Playwright E2E

on:
  push:
    branches: [ main, master, develop, proxy-img-ui-fixes-clean-for-pr ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Start app services
        run: |
          # Start API and Frontend in background; ports should match local dev
          pnpm -s dev:all &
          # wait for server to boot
          npx wait-on http://localhost:3000
        env:
          # Ensure tests use in-repo defaults; override secrets in Actions as needed
          TEST_BASE_URL: http://localhost:3000
        shell: bash

      - name: Run Playwright tests
        uses: microsoft/playwright-github-action@v1
        with:
          run: pnpm -s playwright test --reporter=github

      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
